// app.js - State management and game logic for Airlock Sabotage

let state = {
  oxygen: 100,
  questionsRemaining: 10,
  gameOver: false,
  saboteur: 'jax'
};

const chatLog = document.getElementById('chat-log');
const chatInput = document.getElementById('chat-input');
const oxygenBar = document.getElementById('oxygen-bar');
const oxygenPct = document.getElementById('oxygen-pct');
const interrogationCounter = document.getElementById('interrogation-counter');
const endOverlay = document.getElementById('end-overlay');
const endTitle = document.getElementById('end-title');
const endDesc = document.getElementById('end-desc');

// Mock responses based on keyword matching (Interrogation system)
const suspects = {
  elena: {
    name: "Elena Rostova",
    color: "cyan",
    responses: {
      alibi: "I was in Sector 2 (Reactor Core) troubleshooting a minor power surge from 04:00 to 04:30. You can check the logs, Marcus saw me there briefly at 04:05.",
      jax: "Jax? He's security. He is supposed to be patrolling, but I rarely see him doing actual work. I don't know where he was during the leak.",
      chen: "Dr. Chen is usually in the Greenhouse. She stays out of engineering business, which I appreciate.",
      default: "Look, I've been working double shifts. I was in Sector 2 trying to prevent a reactor melt. What exactly are you implying?"
    }
  },
  marcus: {
    name: "Marcus Vance",
    color: "gold",
    responses: {
      alibi: "I was doing routine maintenance in Sector 2. Passed Elena around 04:05. Then I headed to the Lounge in Sector 5 to grab a coffee at 04:10 and stayed there alone until the alarm rang.",
      jax: "Jax? Didn't see him in the Reactor Room, and he definitely wasn't in the lounge when I was drinking coffee.",
      chen: "Dr. Chen is cool. A bit obsessive about her plants, but she doesn't bother anyone.",
      default: "I was just trying to get some caffeine in my system. Ask the station computer if you don't believe my alibi."
    }
  },
  chen: {
    name: "Dr. Mei-Ling Chen",
    color: "emerald",
    responses: {
      alibi: "I was in the Greenhouse (Sector 4) checking hydroponic nutrient levels from 04:00 onwards. I was working alone.",
      jax: "Jax? No, I haven't seen Jax since yesterday afternoon. Why do you ask? Was he supposed to be in the Greenhouse?",
      chen: "Yes, I was checking the hydroponic systems. They require constant calibration.",
      default: "I was alone in the greenhouse. The plants require quiet concentration. I did not see or hear anyone else until the sirens went off."
    }
  },
  jax: {
    name: "Jax Thorne",
    color: "rose",
    responses: {
      alibi: "I was in Sector 4 (Greenhouse) helping Dr. Chen move some heavy soil and equipment crates from 04:10 to 04:20. Standard security assistance.",
      jax: "I was doing my duty. Standard patrol, followed by assisting the science staff in the greenhouse.",
      chen: "Yeah, Dr. Chen was in the Greenhouse. I was helping her with the equipment crates at 04:15 when the line blew.",
      default: "I was on duty. Security sweeps. Nothing unusual on my end until the decompression alarm sounded."
    }
  }
};

// Form submit handler
function handleQuestionSubmit(event) {
  event.preventDefault();
  if (state.gameOver) return;

  const questionText = chatInput.value.trim();
  if (!questionText) return;

  // 1. Add User message to chat
  appendMessage("COMMANDER (YOU)", questionText, "user");
  chatInput.value = "";

  // 2. Reduce Oxygen and Interrogation count
  state.oxygen -= 10;
  state.questionsRemaining -= 1;
  updateStatusUI();

  // 3. Process replies after a short delay
  setTimeout(() => {
    generateReplies(questionText);
  }, 800);
}

// Generate suspect responses
async function generateReplies(question) {
  let data = null;
  try {
    const response = await fetch("http://localhost:8080/api/interrogate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ question: question })
    });
    if (response.ok) {
      data = await response.json();
    } else {
      console.warn("Backend API error, falling back to local simulation.");
    }
  } catch (err) {
    console.warn("Backend server offline, falling back to local simulation.");
  }

  if (data) {
    // Append the dynamic responses generated by the Antigravity Agent
    Object.keys(suspects).forEach(key => {
      const suspect = suspects[key];
      const text = data[key] || "No comment.";
      appendMessage(suspect.name, text, "suspect", suspect.color);
    });
  } else {
    // Fallback local response generator
    const query = question.toLowerCase();
    let category = "default";

    if (query.includes("where") || query.includes("alibi") || query.includes("time") || query.includes("happen") || query.includes("incident") || query.includes("doing") || query.includes("04:15")) {
      category = "alibi";
    } else if (query.includes("jax") || query.includes("security") || query.includes("guard")) {
      category = "jax";
    } else if (query.includes("chen") || query.includes("botanist") || query.includes("greenhouse") || query.includes("plants")) {
      category = "chen";
    }

    Object.keys(suspects).forEach(key => {
      const suspect = suspects[key];
      const text = suspect.responses[category] || suspect.responses.default;
      appendMessage(suspect.name, text, "suspect", suspect.color);
    });
  }

  // Check loss condition (out of questions)
  if (state.questionsRemaining <= 0 && !state.gameOver) {
    triggerEndGame(false, "OXYGEN DEPLETED", "You ran out of interrogation opportunities. The station's life support failed completely, and the saboteur escaped in the chaos.");
  }
}

// Helper to append chat message HTML
function appendMessage(sender, text, type, colorClass = "") {
  const bubbleContainer = document.createElement("div");
  bubbleContainer.className = `chat-bubble-container ${type}`;

  const nameSpan = document.createElement("div");
  nameSpan.className = "chat-name";
  if (colorClass) {
    nameSpan.innerHTML = `<span class="pulse-dot" style="background-color: var(--${colorClass}); box-shadow: 0 0 5px var(--${colorClass});"></span>${sender}`;
  } else {
    nameSpan.innerText = sender;
  }

  const bubble = document.createElement("div");
  bubble.className = "chat-bubble";
  bubble.innerText = text;

  bubbleContainer.appendChild(nameSpan);
  bubbleContainer.appendChild(bubble);
  chatLog.appendChild(bubbleContainer);

  // Scroll to bottom
  chatLog.scrollTop = chatLog.scrollHeight;
}

// Update UI headers
function updateStatusUI() {
  oxygenBar.style.width = `${state.oxygen}%`;
  oxygenPct.innerText = `${state.oxygen}%`;
  interrogationCounter.innerText = `${state.questionsRemaining} / 10 REMAINING`;

  // Flash red warning if oxygen is low
  if (state.oxygen <= 30) {
    oxygenBar.style.backgroundColor = "var(--alert-red)";
    document.querySelector('.progress-bar-container').style.border = "1px solid var(--alert-red)";
  } else {
    oxygenBar.style.backgroundColor = "";
    document.querySelector('.progress-bar-container').style.border = "";
  }
}

// Vent button action
function ventSuspect(suspectKey) {
  if (state.gameOver) return;

  if (suspectKey === state.saboteur) {
    // Victory!
    triggerEndGame(true, "SABOTEUR NEUTRALIZED", `Excellent work, Commander. You successfully identified Jax Thorne as the saboteur. He was ejected through the airlock, and the remaining crew has repaired the oxygen feed. The station is secure.`);
  } else {
    // Defeat (wrong choice)
    const victim = suspects[suspectKey].name;
    triggerEndGame(false, "MISSION FAILED", `Fatal error. You vented ${victim}, who was innocent. With life support failing and key personnel lost, the actual saboteur (Jax Thorne) successfully disabled the remaining backup systems. The station went dark.`);
  }
}

// Trigger game over overlay
function triggerEndGame(isVictory, title, description) {
  state.gameOver = true;
  endOverlay.classList.remove('hidden');
  endTitle.innerText = title;
  endTitle.className = isVictory ? "victory-title" : "defeat-title";
  endDesc.innerText = description;
}

// Reset / Restart game state
function resetGame() {
  state.oxygen = 100;
  state.questionsRemaining = 10;
  state.gameOver = false;

  updateStatusUI();
  
  // Clear chat logs except first system broadcast
  chatLog.innerHTML = `
    <div class="system-message">
      <p>[SYSTEM DETECTED]: OXYGEN LINE SEVERED IN SECTOR 7 AT 04:15. ALL CREW ORDERED TO QUARANTINE. CHAT TERMINAL ESTABLISHED.</p>
      <p>[INSTRUCTION]: ASK QUESTIONS TO LOCATE THE CONTRADICTION. CHOOSE WISELY. VENTING IS FINAL.</p>
    </div>
  `;
  
  endOverlay.classList.add('hidden');
}
